update README.md
docascode/vscode-docs-build pull request #193
Opened 2021-01-11 07:19 UTC by shanluo911

AB#358291

2021-01-11 08:37 UTC, 928PJY submitted a review, later dismissed

2021-01-12 10:32 UTC, herohua commented on README.md
> +4. The real-time validation is disabled by default, you can enable it in the extension settings. You will be suggested to reload the extension after you enable real-time validation.
`You will be asked to reload the extension after you enable real-time validation in the settings.`

2021-01-12 10:33 UTC, herohua approved these changes

2021-01-15 05:33 UTC, 928PJY commented on README.md
> +1. After signing in, you can trigger a validation by clicking **Yes** when prompted. You can also click **Docs Validation** on the status bar then click **Validate** from the drop-down menu, or by ri
do we have a `Yes` button?

2021-01-15 05:33 UTC, 928PJY commented on README.md
> +1. For the first time you use the extension, you will be suggested to choose your user type between **Microsoft employee** and **Public contributor** before you can use full-repository validation.
`you will be asked to choose..`

2021-01-15 05:33 UTC, 928PJY commented on README.md
> +3. For **Microsoft employee**, you are required to sign in before using real-time validation. You can click **Docs Validation** on the status bar then click **Sign in** from the drop-down menu to sig
This may confuse the user that they may need to `sign-in` manually.

2021-01-15 05:33 UTC, 928PJY commented on README.md
> +4. The real-time validation is disabled by default, you can enable it in the extension settings. You will be suggested to reload the extension after you enable real-time validation.
let's also add an instruction about how to enable the flag

2021-01-15 05:56 UTC, shanluo911 commented on README.md
> +1. After signing in, you can trigger a validation by clicking **Yes** when prompted. You can also click **Docs Validation** on the status bar then click **Validate** from the drop-down menu, or by ri
change to **Validate**

2021-01-15 09:19 UTC, 928PJY reviewed
🏎

2021-01-15 09:19 UTC, 928PJY requested changes
🏎

2021-01-15 09:31 UTC, 928PJY approved these changes

2021-01-15 09:36 UTC, merged