Release 0.3.3
docascode/vscode-docs-build pull request #233
Opened 2021-03-25 09:32 UTC by 928PJY

Depends on #230

2021-03-26 02:07 UTC, shanluo911 commented on README.md
> +### Manual validation
Not sure, but I think maybe 'manual(ly) triggered validation' is better?

2021-03-26 06:33 UTC, herohua requested changes
Hold off this release until PM confirms

2021-03-31 02:33 UTC, shanluo911 commented on CHANGELOG.md
> +- Support Activating extension when the user is on the sub-folder of Docs repository. (#209)
typo lower case `a`

2021-03-31 02:34 UTC, shanluo911 commented on CHANGELOG.md
> +- Support trigger validation on the sub-folder of the current repository. (#229)
triggering

2021-03-31 02:36 UTC, shanluo911 commented on README.md
> +You can trigger the validation manually with the following options:
remove `the`

2021-03-31 02:37 UTC, shanluo911 commented on README.md
> +1. You three ways to trigger the manual validation:
there are

2021-03-31 02:38 UTC, shanluo911 commented on README.md
> +   2. You can click **Docs Validation** on the status bar then click **Validate the current workspace** or **Validate the whole repository** from the drop-down menu to trigger the validation on diffe
scopes

2021-03-31 02:39 UTC, shanluo911 commented on README.md
> +   3. You can right-clicking any file/folder inside the **Explorer** and selecting **Validate this folder**, if you click on the file, the validation will be applied to the folder contains the select
right-click

2021-04-06 02:04 UTC, shanluo911 approved these changes

2021-04-06 02:04 UTC, merged